### PR TITLE
Stage 1 Submission

### PR DESCRIPTION
**Pull request by Gaktines**

### CODE REVIEW

**Comment by Gaktines** [comment]
It's deployed on gh pages.

**Comment by Gaktines** [comment]
I already fixed the other issues.  I am not making the signup and signin work as I'm only doing the frontend for the final project and the tutor said I don't need them working.

**Comment by FiLLa-FaS** [comment]
Yep, you don't need them working, but click on the submit button with filled inputs ends with error https://pasteboard.co/Xj7qDj3HcTzZ.png. It's a bad behaviour, you need to make submit functions empty without any logic and errors - so I click on submit button and nothing happens or you can close the popup window if you want

I'll add the full review soon, please don't change anything until I'll add here full review. Thanks!

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for submitting your project for the first review, I'm glad that you've deployed project and API data is loading correctly. I left some comments below and hope that they help you to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

#### Markup and JSX
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages shouldn't have horizontal scrolling on 320px+ screen resolutions
    * All page content should be centered on all screen resolutions
    * All content shouldn't extend outside their containers on all screen resolutions
    * All your page content should have some layout - all elements should be ordered on the page, all similar items should have similar content places and spaces between them (now job cards have content in different places of its card)
    * Popups shouldn't be very narrow on all screen resolutions
    * Page content should have at least small side spaces on all screen resolutions
    * Incorrect location of the footer (it shouldn't overlap the page content)
- [ ]  Navigation between pages and links to external resources are working correctly. There are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and there are no hidden blocks.
    * Job link should be opened in a new tab
- [x]  Elements specified in the UI toolkit are used correctly (e.g., buttons, forms, text elements, etc).
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside its BEM block (for example you can't use `header__desktop` class outside the `header`). Please fix all similar cases **throughout the project**
    * BEM modifiers classes should be used only with their base classes **throughout the project**
    * You should use BEM key-values modifiers instead of boolean for `header__nav_button-signup` and `header__nav_button-signin` classes.
    * You need to use BEM element class for `card_job` and `modal_header` items
    * Please don't use capital letters in class names
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You should use correct semantic tags for text elements inside `card` block, for elements inside `footer`
- [ ]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
    * Footer shouldn't be placed using absolute positioning
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has erorrs and warnings in browser console and in the VS Code terminal

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`.
- [x]  No third-party JavaScript libraries are used, unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with `addEventListener` are removed when the component is unmounted.
- [ ]  API error handling:
  - [ ] The user receives a message in the case of an error.
      * Note, that console log is not a message for user - you need to create a UI message, so user can see it if something goes wrong
- [ ]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
    * You have constants in `utils` folder - you need to move them to a new file and rename using only capital letters
- [ ]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed using the cross button, overlay, or ESC key.
    * Popup can't be closed using the overlay

### Recommendations

#### Markup and JSX
- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [ ]  The code is clean and easy to understand:
  - The code is readable and clearly structured. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, when a variable is declared but not used, or there is some kind of redundant logic.
      * You have some extra values, and empty files and unfinished logic - you should have only clean finished project features
  - The code is formatted in the same way, and the indentation hierarchy is respected.

## Number of points: 65

**Comment by Gaktines** [comment]
I think I have everything fixed to include the signup and signin modals.

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections, your project looks better! I left several comments below. Good luck!✨

# Summary:
### Performance Criteria

#### Markup and JSX
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages shouldn't have horizontal scrolling on 601px+ screen resolutions
    * You've used burger for small screen resolutions, it's a good practive, but you need to make sure that I can click on the burger and open the nav menu with all hidden header tabs
    * All content shouldn't extend outside their containers on all screen resolutions https://pasteboard.co/IV9QCHzFZRie.png
    * Text elements in job card shouldn't overlap each other https://pasteboard.co/jbpJeRdspY2Q.png
    * Page content should have at least small side spaces on all screen resolutions (you can see the example on the screenshot https://pasteboard.co/DCZTN4XFbm6a.png, but you should fix all similar cases **throughout the project**)
    page content shouldn't stretch on more than 1440px screen resolution, it should keep its layout
- [x]  Navigation between pages and links to external resources are working correctly. There are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and there are no hidden blocks.
- [x]  Elements specified in the UI toolkit are used correctly (e.g., buttons, forms, text elements, etc).
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside its BEM block (for example you can't use `card__block` class outside the `card`). **Please fix all similar cases throughout the project**
    * You need to use BEM element class for `card_job` item
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You should use correct semantic tags for text elements inside `card` block, for elements inside `footer`
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has eslint warnings

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`.
- [x]  No third-party JavaScript libraries are used, unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with `addEventListener` are removed when the component is unmounted.
- [ ]  API error handling:
  - [ ] The user receives a message in the case of an error.
      * Note, that console log is not a message for user - you need to create a UI message, so user can see it if something goes wrong
- [ ]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
    * All constants should be named in all capital letters and moved to `constants.js` file inside `utils` folder
- [ ]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed using the cross button, overlay, or ESC key.
    * Popup can't be closed using the overlay

### Recommendations

#### Markup and JSX
- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All font-family styles should have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and clearly structured. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, when a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, and the indentation hierarchy is respected.

## Number of points: 77

**Comment by FiLLa-FaS** [comment]
# Summary:
### Performance Criteria

#### Markup and JSX
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages shouldn't have horizontal scrolling on 601px+ screen resolutions
    * You've used burger for small screen resolutions, it's a good practive, but you need to make sure that I can click on the burger and open the nav menu with all hidden header tabs
    * All content shouldn't extend outside their containers on all screen resolutions https://pasteboard.co/rrNgWkDccKoJ.png
    * All items in job cards should be structured similar https://pasteboard.co/qudzvePfSgYT.png
    * page content shouldn't stretch on more than 1440px screen resolution, it should keep its layout
- [x]  Navigation between pages and links to external resources are working correctly. There are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and there are no hidden blocks.
- [x]  Elements specified in the UI toolkit are used correctly (e.g., buttons, forms, text elements, etc).
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside its BEM block (for example you can't use `card__block` class outside the `card`). Please fix all similar cases throughout the project
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * You should use correct semantic tag for `card__job-pubdate` instead of `div`
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * Project has eslint warnings, you can find them in the VSCode terminal

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`.
- [x]  No third-party JavaScript libraries are used, unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with `addEventListener` are removed when the component is unmounted.
- [ ]  API error handling:
  - [ ] The user receives a message in the case of an error.
      * Note, that console log is not a message for user - you need to create a UI message, so user can see it if something goes wrong
- [ ]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
    * All constants should be named in all capital letters and moved to `constants.js` file inside `utils` folder
- [x]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed using the cross button, overlay, or ESC key.

### Recommendations

#### Markup and JSX
- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All font-family styles should have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and clearly structured. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, when a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, and the indentation hierarchy is respected.

## Number of points: 78

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm glad to accept your project. BTW you still can fix the rest issues to improve your project. Good luck!🙌🚀

# Summary:
### Performance Criteria

#### Markup and JSX
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions. There is no horizontal scrolling on resolutions of `320px` and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages shouldn't have horizontal scrolling on 801px+ screen resolutions and on smaller screen resolutions when the mobile burger is opened
    * page content shouldn't stretch on more than 1440px screen resolution, it should keep its layout
- [x]  Navigation between pages and links to external resources are working correctly. There are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and there are no hidden blocks.
- [x]  Elements specified in the UI toolkit are used correctly (e.g., buttons, forms, text elements, etc).
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

#### React
- React components:
  - [x]  Hooks are not used inside conditional statements or loops.
  - [x]  Hooks are called in a component's main function.
  - [x]  For class components, effects are described inside the component lifecycle methods.
- [x]  Asynchronous API requests:
  - Requests can be made through the Fetch API or by using XMLHttpRequest. Third-party libraries (such as axios or jQuery) are not used.
  - API requests are contained in a separate file.
  - The chain for processing promises ends with a `catch()` block.
  - The first `then()` handler returns `res.json`.
- [x]  Naming:
  - camelCase is used for function and variable names.
  - Only nouns are used as variable names.
  - Variable names clearly describe what is stored in them. If the project has several variables with similar data, then those variables have unique but descriptive names.
  - Descriptive names are used for functions, which reflect what they do.
  - Function names start with a verb.
  - JS classes and functional components are named using nouns and start with a capital letter.
  - Names must not include inappropriate or unclear abbreviations.
  - Сustom hook names start with `use`.
- [x]  No third-party JavaScript libraries are used, unless absolutely necessary. If third-party libraries are connected, then they are used appropriately.

### Best Practices

#### Markup and JSX
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

#### React
- [x]  The initial state of state variables contain the correct data type.
- [x]  API requests are described inside the `App` component.
- [x]  There is no memory leak when hanging handlers. All handlers added with `addEventListener` are removed when the component is unmounted.
- [ ]  API error handling:
  - [ ] The user receives a message in the case of an error.
      * Note, that console log is not a message for user - you need to create a UI message, so user can see it if something goes wrong
- [ ]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.
    * All constants should be named in all capital letters and moved to `constants.js` file inside `utils` folder
- [x]  If you are using popups, then correct the opening and closing functionality is implemented. Popups can be closed using the cross button, overlay, or ESC key.

### Recommendations

#### Markup and JSX
- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All font-family styles should have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

#### React
- [x]  For internal links in the application, components from the react-router library are used.
- [x]  Semantically correct blocks are used for components. No `<div />` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [x]  The code is clean and easy to understand:
  - The code is readable and clearly structured. Some parts of the code are explained with comments if needed.
  - There is no extra code: for example, when a variable is declared but not used, or there is some kind of redundant logic.
  - The code is formatted in the same way, and the indentation hierarchy is respected.

## Number of points: 89

**Pull request merged**
